version: '3'
services:
  db:
    image: postgres
    ports:
    - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: movies

volumes:
  postgres_data: